spring.application.name=Content-Calender
spring.datasource.name=content
spring.datasource.generate-unique-name=false
logging.level.org.springframework.jdbc=DEBUG
spring.h2.console.enabled=true

cc.welcomeMessage=Welcome to Calender website!
cc.desc=This is collection of my blogs

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always